import type { Project } from "@/types";

export const projectsData: Project[] = [
  {
    id: "ecommerce-ai-agent",
    title: "E-commerce AI Agent",
    period: "08/2025 — 01/2026 · Team 3 người",
    team: "Team 3 người",
    image: "/project1.png",
    tech: [
      "Next.js",
      "Tailwind CSS",
      "TypeScript",
      "CopilotKit",
      "Supabase (PostgreSQL)",
      "Google ADK",
      "FastAPI",
    ],
    description: "Web bán hàng tích hợp AI Agent tư vấn sản phẩm cho khách hàng, hỗ trợ trải nghiệm mua sắm thông minh.",
    roles: [
      "Sử dụng Next.js làm frontend",
      "CopilotKit làm frontend tool cho Agent",
      "Thiết kế database & hỗ trợ triển khai",
      "Thiết kế và triển khai backend bằng FastAPI",
      "Giao tiếp với team để thống nhất ý tưởng và triển khai",
    ],
    learnings: "Cấu trúc AI Agent, MCP, AgUI, SSR, ISR",
    liveUrl: "https://copilot-chan-fe-v2.vercel.app/",
    githubUrl: "https://github.com/copilot-chan/copilot-chan-fe-v2",
    reverse: false,
  },
  {
    id: "interactive-novel",
    title: "Interactive Novel",
    period: "03/2025 — 05/2025 · Team 3 người",
    team: "Team 3 người",
    image: "/project2.png",
    tech: ["React", "Vite", "Express", "PostgreSQL"],
    description: "Website cho phép tạo câu chuyện được sinh ra bởi AI, người dùng có thể dẫn dắt mạch truyện theo ý muốn.",
    roles: [
      "Sử dụng React làm frontend",
      "Hỗ trợ chức năng Auth Google",
      "Hỗ trợ thiết kế database",
    ],
    learnings: "Quản lý state cơ bản trong frontend, Custom Hook",
    liveUrl: "https://visual-story.vercel.app/",
    githubUrl: "https://github.com/vucongchien/visual-story",
    reverse: false,
  },
  {
    id: "my-dress-up-darling",
    title: "My Dress Up Darling",
    period: "03/2025 · Team 3 người · 12 ngày",
    team: "Team 3 người · 12 ngày",
    image: "/project3.png",
    tech: ["HTML", "CSS", "JavaScript"],
    description: "Website giới thiệu bộ anime My Dress Up Darling với giao diện đẹp mắt và trải nghiệm trực quan.",
    roles: [
      "Thiết kế Figma",
      "Làm page Comics",
      "Hỗ trợ viết code HTML cho page Home",
    ],
    learnings: "Layout trong CSS, các thẻ HTML, Tailwind cơ bản",
    liveUrl: "https://vucongchien.github.io/BTWEB/",
    githubUrl: "https://github.com/vucongchien/BTWEB",
    reverse: false,
  },
];
