import type { Project } from "@/types";

export const projectsData: Project[] = [
  {
    id: "ecommerce-ai-agent",
    title: "E-commerce AI Agent",
    period: "08/2025 — 01/2026 · Team of 3",
    team: "Team of 3",
    image: "/project1.png",
    tech: [
      "Next.js",
      "TypeScript",
      "FastAPI",
      "REST API",
      "Supabase",
      "TailwindCSS",
      "AgUI",
    ],
    description: "Designed and developed a modern end-to-end food e-commerce platform, enabling users to browse products, manage carts, and place orders with a focus on reliability and performance optimization.",
    roles: [
      "Build responsive frontend features with Next.js and TypeScript, integrating seamlessly with backend APIs",
      "Developed AI agent frontend tooling and interactive workflows using AG-UI",
      "Thiết kế CSDL Supabase và phát triển backend bằng FastAPI & REST API",
    ],
    learnings: "Cấu trúc AI Agent, MCP, AgUI, SSR, ISR",
    liveUrl: "https://copilot-chan-fe-v2.vercel.app/",
    githubUrl: "https://github.com/copilot-chan/copilot-chan-fe-v2",
    reverse: false,
  },
  {
    id: "interactive-novel",
    title: "Interactive Novel",
    period: "03/2025 — 05/2025 · Team of 3",
    team: "Team of 3",
    image: "/project2.png",
    tech: [
      "React",
      "FastAPI",
      "REST API",
      "TailwindCSS",
      "OAuth",
      "Docker",
      "Fly.io",
    ],
    description: "Built the frontend of an end-to-end interactive storytelling platform, with a focus on user experience, delivering a modern, responsive, and intuitive interface.",
    roles: [
      "Developed backend services with FastAPI, designing RESTful APIs for story retrieval and user management",
      "Integrating the Gemini API with prompt-engineering to generate dynamic, AI-driven story content",
      "Phát triển giao diện tương tác và xác thực OAuth",
    ],
    learnings: "Prompt Engineering, Gemini API, FastAPI REST API, Custom Hooks",
    liveUrl: "https://visual-story.vercel.app/",
    githubUrl: "https://github.com/vucongchien/visual-story",
    reverse: false,
  },
  {
    id: "my-dress-up-darling",
    title: "My Dress Up Darling",
    period: "03/2025 · Team 3 người · 12 ngày",
    team: "Team 3 người · 12 ngày",
    image: "/project3.png",
    tech: ["HTML", "CSS", "JavaScript"],
    description: "Website giới thiệu bộ anime My Dress Up Darling với giao diện đẹp mắt và trải nghiệm trực quan.",
    roles: [
      "Thiết kế Figma",
      "Làm page Comics",
      "Hỗ trợ viết code HTML cho page Home",
    ],
    learnings: "Layout trong CSS, các thẻ HTML, Tailwind cơ bản",
    liveUrl: "https://vucongchien.github.io/BTWEB/",
    githubUrl: "https://github.com/vucongchien/BTWEB",
    reverse: false,
  },
];
